name: Backend CI

on:
  push:
    branches: [ main, develop, Pruebas ]
  pull_request:
    branches: [ main, develop, Pruebas ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: expenses
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/expenses
      GEMINI_API_KEY: dummy_key

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pip install pytest pytest-cov
          pytest backend/tests \
            --cov=backend/app \
            --cov-report=term-missing \
        env:
          PYTHONPATH: ${{ github.workspace }}/backend

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
            -t backend-image ./backend